//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 12:15:46 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://rafal/types", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package rt.eureka.importy;
