//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 12:39:26 PM CET 
//


package rt.eureka.importy;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for powiazanie complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="powiazanie"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="relacjaPowiazania" type="{http://rafal/types}relacjaPowiazania" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="statusFailedMessage" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "powiazanie", propOrder = {
    "relacjaPowiazania"
})
public class Powiazanie {

    @XmlElement(required = true)
    protected List<RelacjaPowiazania> relacjaPowiazania;
    @XmlAttribute(name = "statusFailedMessage", required = true)
    protected String statusFailedMessage;

    /**
     * Gets the value of the relacjaPowiazania property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relacjaPowiazania property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelacjaPowiazania().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelacjaPowiazania }
     * 
     * 
     */
    public List<RelacjaPowiazania> getRelacjaPowiazania() {
        if (relacjaPowiazania == null) {
            relacjaPowiazania = new ArrayList<RelacjaPowiazania>();
        }
        return this.relacjaPowiazania;
    }

    /**
     * Gets the value of the statusFailedMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusFailedMessage() {
        return statusFailedMessage;
    }

    /**
     * Sets the value of the statusFailedMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusFailedMessage(String value) {
        this.statusFailedMessage = value;
    }

}
