//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 12:39:26 PM CET 
//


package rt.eureka.importy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for relacjaPowiazania complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="relacjaPowiazania"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="uslugaId" use="required" type="{http://rafal/types}idType" /&gt;
 *       &lt;attribute name="status" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="operacja" type="{http://rafal/types}operacjeType" /&gt;
 *       &lt;attribute name="badel" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "relacjaPowiazania")
public class RelacjaPowiazania {

    @XmlAttribute(name = "uslugaId", required = true)
    protected long uslugaId;
    @XmlAttribute(name = "status", required = true)
    protected String status;
    @XmlAttribute(name = "operacja")
    protected OperacjeType operacja;
    @XmlAttribute(name = "badel", required = true)
    protected boolean badel;

    /**
     * Gets the value of the uslugaId property.
     * 
     */
    public long getUslugaId() {
        return uslugaId;
    }

    /**
     * Sets the value of the uslugaId property.
     * 
     */
    public void setUslugaId(long value) {
        this.uslugaId = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the operacja property.
     * 
     * @return
     *     possible object is
     *     {@link OperacjeType }
     *     
     */
    public OperacjeType getOperacja() {
        return operacja;
    }

    /**
     * Sets the value of the operacja property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperacjeType }
     *     
     */
    public void setOperacja(OperacjeType value) {
        this.operacja = value;
    }

    /**
     * Gets the value of the badel property.
     * 
     */
    public boolean isBadel() {
        return badel;
    }

    /**
     * Sets the value of the badel property.
     * 
     */
    public void setBadel(boolean value) {
        this.badel = value;
    }

}
