//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.20 at 12:39:26 PM CET 
//


package rt.eureka.importy;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for uslugaLinkiType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="uslugaLinkiType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="powiazanie" type="{http://rafal/types}powiazanie" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="uslugaId" use="required" type="{http://rafal/types}idType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "uslugaLinkiType", propOrder = {
    "powiazanie"
})
public class UslugaLinkiType {

    @XmlElement(required = true)
    protected List<Powiazanie> powiazanie;
    @XmlAttribute(name = "uslugaId", required = true)
    protected long uslugaId;

    /**
     * Gets the value of the powiazanie property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the powiazanie property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPowiazanie().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Powiazanie }
     * 
     * 
     */
    public List<Powiazanie> getPowiazanie() {
        if (powiazanie == null) {
            powiazanie = new ArrayList<Powiazanie>();
        }
        return this.powiazanie;
    }

    /**
     * Gets the value of the uslugaId property.
     * 
     */
    public long getUslugaId() {
        return uslugaId;
    }

    /**
     * Sets the value of the uslugaId property.
     * 
     */
    public void setUslugaId(long value) {
        this.uslugaId = value;
    }

}
